version: '3'
services:
  docsify:
    restart: unless-stopped
    build: ./
    container_name: docsify_test
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
        - ./docs:/docsify
    working_dir: /docsify
    command: docsify serve . -p 3000 --livereload-port 35729