version: '3.3'
services:
  docsify:
    image: buenzlis/docsify-js:latest
    container_name: docsify-js
    restart: unless-stopped
    ports:
       - "3000:3000"
       - "35729:35729"
    volumes:
       - ./docs:/docsify
    working_dir: /docsify
    command: docsify serve . -p 3000 --livereload-port 35729
